// Vue/20-脚手架/hello_vue/24_src_多级路由/App.vue
<template>


<div>
    <div class="row">
        <banner/>
    </div>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <div class="list-group">
            <!-- 原始html中我们使用a标签实现页面跳转 -->
          <!-- <a class="list-group-item active" href="./about.html">About</a>
          <a class="list-group-item" href="./home.html">Home</a> -->

            <!-- vue中借助router-link标签实现路由的切换 -->
          <router-link class="list-group-item" active-class="active" to="/about">About</router-link>
          <router-link class="list-group-item" active-class="active" to="/home">Home</router-link>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel">
          <div class="panel-body">
              <!-- 指定路由的呈现位置 -->
             <router-view></router-view>
          </div>
        </div>
      </div>
    </div>
  </div>


</template>

<script>
// 引入组件
import Banner from './components/Banner.vue'



export default {
    name: "App",
    data() {
      return {
    
      }
    },
    components: { 
        Banner
     }

}
</script>


<style lang="css" scoped>

</style>

// React/Router6/router-six/04-路由表/App.jsx
import React from 'react'

import {NavLink,useRoutes} from 'react-router-dom';

import routes from './routes';

export default function App() {

  // 根据路由表生成对应的路由规则
  const element = useRoutes(routes)

  return (
    <div>
        <div className="row">
        <div className="col-xs-offset-2 col-xs-8">
            <div className="page-header"><h2>React Router Demo</h2></div>
        </div>
        </div>
        <div className="row">
        <div className="col-xs-2 col-xs-offset-2">
            <div className="list-group">
            {/* 路由链接 */}
            <NavLink className="list-group-item" to="/about">About</NavLink>
            <NavLink className="list-group-item" to="/home">Home</NavLink>
            </div>
        </div>
        <div className="col-xs-6">
            <div className="panel">
            <div className="panel-body">
                {/* 注册路由 */}
                {element}
            </div>
            </div>
        </div>
        </div>
    </div>
  )
}
