// React/ReactStaging/hello-react/15-嵌套路由的使用/pages/Home/Message/index.jsx
import React, { Component } from 'react'

export default class Message extends Component {
  render() {
    return (
       <div>
            <ul>
                <li>
                    <a href="/message1">message001</a>&nbsp;&nbsp;
                </li>
                <li>
                    <a href="/message2">message002</a>&nbsp;&nbsp;
                </li>
                <li>
                    <a href="/message/3">message003</a>&nbsp;&nbsp;
                </li>
            </ul>
      </div>
    )
  }
}

// Vue/20-脚手架/hello_vue/24_src_多级路由/pages/Message.vue
<template>
  <div>
        <ul>
            <li>
                <a href="/message1">message001</a>&nbsp;&nbsp;
             </li>
             <li>
               <a href="/message2">message002</a>&nbsp;&nbsp;
             </li>
              <li>
               <a href="/message/3">message003</a>&nbsp;&nbsp;
            </li>
       </ul>
   </div>
</template>

<script>
export default {
    name:'Message'
}
</script>

<style>

</style>
