// Vue/20-脚手架/hello_vue/17_src_github搜索案例/components/List.vue
<template>
      <div class="row">
          <!-- 展示用户列表 -->
      <div v-show="info.users.length" class="card" v-for="user in info.users" :key="user.login">
        <a :href="user.html_url" target="_blank">
          <img :src="user.avatar_url" style='width: 100px'/>
        </a>
        <p class="card-text">{{user.login}}</p>
      </div>
    <!-- 展示欢迎词 -->
    <h1 v-show="info.isFirst">欢迎使用</h1>
    <!-- 展示加载中 -->
    <h1 v-show="info.isLoading">加载中...</h1>
    <!-- 展示错误信息 -->
    <h1 v-show="info.errMsg">{{info.errMsg}}</h1>
    </div>

</template>

<script>
export default {
    name:'List',
    data() {
        return {
           info:{
            users:[],
            isFirst:true,
            isLoading:false,
            errMsg:''
           }
        }
    },
    mounted() {
        this.$bus.$on('upDateListDate',(dataObj)=>{
            // console.log('我是list组件,收到了数据',users);
            console.log(dataObj);
            this.info = {...this.info,...dataObj};
            // this.users=users;
            // this.isFirst=isFirst;
            // this.errMsg=errMsg;
            // this.isLoading=isLoading;
        })  
    },
}
</script>

<style scoped>
.album {
  min-height: 50rem; /* Can be removed; just added for demo purposes */
  padding-top: 3rem;
  padding-bottom: 3rem;
  background-color: #f7f7f7;
}

.card {
  float: left;
  width: 33.333%;
  padding: .75rem;
  margin-bottom: 2rem;
  border: 1px solid #efefef;
  text-align: center;
}

.card > img {
  margin-bottom: .75rem;
  border-radius: 100px;
}

.card-text {
  font-size: 85%;
}
</style>

// React/ReactStaging/hello-react/05-github用户搜索案例/components/List/index.jsx
import React, { Component } from 'react'

export default class List extends Component {



  render() {
    const {users,isFirst,isLoading,err}=this.props
    return (
      <div className="row">
        {
          isFirst ? <h2>欢迎使用</h2> :
          isLoading ? <h2>Loading...</h2> :
          err ? <h2 style={{color:'red'}}>{err}</h2> :
          users.map((usersObj)=>{
            return (
              <div key={usersObj.id} className="card">
                  <a rel="noreferrer" href={usersObj.html_url} target="_blank">
                    <img alt='pop' src={usersObj.avatar_url} style={{width: '100px'}}/>
                  </a>
                  <p className="card-text">{usersObj.login}</p>
              </div>
            )
          })
        }
      </div>
    )
  }
}
