// React/ReactStaging/hello-react/16-params传递参数/pages/Home/index.jsx
import React, { Component } from 'react'
import News from './News'
import Message from './Message'
import MyNavLink from '../../components/MyNavLink'
import {Route,Switch,Redirect} from 'react-router-dom'

export default class Home extends Component {
  render() {
    return (
      <div>
          <h3>我是Home的内容</h3>
          <div>
              <ul className="nav nav-tabs">
                <li>
                  {/* <a className="list-group-item active" href="./home-news.html">News</a> */}
                  <MyNavLink to="/home/news">News</MyNavLink>
                </li>
                <li>
                  {/* <a className="list-group-item " href="./home-message.html">Message</a> */}
                  <MyNavLink to="/home/message">Message</MyNavLink>
                </li>
              </ul>
             <Switch>
               <Route path="/home/news" component={News}></Route>
               <Route path="/home/message" component={Message}></Route>
               <Redirect to="/home/news"/>
             </Switch>
          </div>
      </div>
    )
  }
}

// Vue/20-脚手架/hello_vue/25_src_命名路由/pages/Home.vue
<template>
       <div>
              <h2>Home组件内容</h2>
           <div>
                <ul class="nav nav-tabs">
                  <li>
                    <router-link class="list-group-item " active-class="active" to="/home/news">News</router-link>
                  </li>
                  <li>
                    <router-link class="list-group-item " active-class="active" to="/home/message">Message</router-link>
                  </li>
                </ul>
               <router-view></router-view>
           </div>
     </div>
</template>

<script>
export default {
    name:'Home',

    mounted(){
      console.log(this);
    }

}
</script>

<style>

</style>
