// React/Router6/router-six/09-编程式路由导航/pages/Home.jsx
import React from 'react'
import {NavLink,Outlet} from 'react-router-dom'


export default function Home() {
  return (
    <div>
      <h1>我是Home</h1>
      <div>
          <ul className="nav nav-tabs">
            <li>
              <NavLink className="list-group-item" to="news">News</NavLink>
            </li>
            <li>
              <NavLink className="list-group-item" to="message">Message</NavLink>
            </li>
          </ul>
          {/* 指定路由组件呈现的位置 */}
          <Outlet/>
        </div>
    </div>
  )
}

// Vue/20-脚手架/hello_vue/25_src_命名路由/pages/Home.vue
<template>
       <div>
              <h2>Home组件内容</h2>
           <div>
                <ul class="nav nav-tabs">
                  <li>
                    <router-link class="list-group-item " active-class="active" to="/home/news">News</router-link>
                  </li>
                  <li>
                    <router-link class="list-group-item " active-class="active" to="/home/message">Message</router-link>
                  </li>
                </ul>
               <router-view></router-view>
           </div>
     </div>
</template>

<script>
export default {
    name:'Home',

    mounted(){
      console.log(this);
    }

}
</script>

<style>

</style>
