// React/Router6/router-six/07-search参数/pages/Message.jsx
import React,{useState}from 'react'
import { Link,Outlet } from 'react-router-dom'

export default function Message() {
  const [message] = useState([
    {id:'001',title:'消息1',content:'one'},
    {id:'002',title:'消息2',content:'two'},
    {id:'003',title:'消息3',content:'three'},
  ])

  return (
    <div>
          <ul>
              {
                message.map((m)=>{
                  return (
                    <li key={m.id}>
                      <Link to={`detail?id=${m.id}&title=${m.title}&content=${m.content}`}>{m.title}</Link>
                    </li>
                  )
                })
              }
          </ul>
          <hr />
          {/* 指定路由组件的展示位置 */}
          <Outlet/>
    </div>
  )
}

// Vue/20-脚手架/hello_vue/25_src_命名路由/pages/Message.vue
<template>
  <div>
        <ul>
            <li v-for="item in messageList" :key="item.id">
                <!-- 跳转路由并携带query参数，to的字符串写法 -->
                <!-- <router-link :to="`/home/message/detail?id=${item.id}&title=${item.title}`">{{item.title}}</router-link>&nbsp;&nbsp; -->

                <!-- 跳转路由并携带query参数，to的对象写法 -->
                <router-link :to="{
                    name:'xiangqing',
                    query:{
                        id:item.id,
                        title:item.title
                    }
                }">
                    {{item.title}}
                </router-link>

             </li>
       </ul>
       <hr>
       <router-view></router-view>
   </div>
</template>

<script>
export default {
    name:'Message',
    data() {
        return {
            messageList:[
                {id:'001',title:'消息001'},          
                {id:'002',title:'消息002'},          
                {id:'003',title:'消息003'},          
            ]
        }
    },
}
</script>

<style>

</style>
