// React/ReactStaging/hello-react/31-打包/containers/Person/index.jsx
import React, { Component } from 'react'

import {nanoid} from 'nanoid'

import {connect} from 'react-redux'

import {createAddPersonAction} from '../../redux/actions/person'

class Person extends Component {
    addPerson=()=>{
        const name = this.nameNode.value;
        const age = this.ageNode.value;
        const personObj={
          id:nanoid(),
          name,
          age
        }
        this.props.add(personObj);

        this.nameNode.value='';
        this.ageNode.value='';
    }
  render() {
    return (
      <div>
        <h2>我是Person组件,上方组件求和为{this.props.he}</h2>
        <input ref={c=>this.nameNode=c} type="text" placeholder='输入名字'/>
        <input ref={c=>this.ageNode=c} type="text" placeholder='输入年龄'/>
        <button onClick={this.addPerson}>添加</button>
        <ul>
            {
              this.props.peops.map((p)=>{
                return <li key={p.id}>{p.name}-----{p.age}</li>
              })
            }
        </ul>
      </div>
    )
  }
}

export default connect(
  state=>({
      peops:state.person, // 映射状态
      he:state.count
  }),
  {add:createAddPersonAction}//映射操作状态的方法
)(Person)

// Vue/20-脚手架/hello_vue/22_src_多组件共享数据/components/Person.vue
<template>
  <div>
      <h3>Count上方组件总和{{sum}}</h3>
      <h1>人员列表</h1>
      <input type="text" placeholder="请输入名字" v-model="name">
      <button @click="add">添加</button>
      <ul>
          <li v-for="p in personList" :key="p.id">{{p.name}}</li>
      </ul>
  </div>
</template>

<script>
import { nanoid } from 'nanoid';
import { mapState } from 'vuex';
export default {
    name:'Person',
    data() {
        return {
            name:''
        }
    },

    computed:{
        personList(){
            return this.$store.state.personList
        },
        sum(){
            return this.$store.state.sum
        }
    },
    methods: {
        add(){
            const personObj={
                id:nanoid(),
                name:this.name
            };
            this.$store.commit('ADD_PERSON',personObj);
            this.name='';

        }
    },
}
</script>

<style>

</style>
