// React/ReactStaging/hello-react/08-路由的基本使用/App.js
import React, { Component } from 'react'
import {Link,BrowserRouter,Route} from 'react-router-dom'

import Home from './components/Home';
import About from './components/About'

export default class App extends Component {
render() {
    return (
      <div>
        <div className="row">
          <div className="col-xs-offset-2 col-xs-8">
            <div className="page-header"><h2>React Router Demo</h2></div>
          </div>
        </div>
        <div className="row">
              <div className="col-xs-2 col-xs-offset-2">
                <div className="list-group">
                  {/* 原生heml中靠a跳转不同页面 */}
                  {/* <a className="list-group-item active" href="./about.html">About</a>
                  <a className="list-group-item" href="./home.html">Home</a> */}
    
                  {/* 在react中靠路由链接实现切换组件-编写路由链接 */}
    
                    <Link className="list-group-item" to="/about">About</Link>
                    <Link className="list-group-item" to="/home">Home</Link>
    
                </div>
              </div>
              <div className="col-xs-6">
                <div className="panel">
                  <div className="panel-body">
                    {/* 注册路由 */}
                    <Route path="/about" component={About}/>
                    <Route path="/home" component={Home}/>
                  </div>
                </div>
              </div>
        </div>
    </div>
    )
  }
}

// Vue/20-脚手架/hello_vue/24_src_多级路由/App.vue
<template>


<div>
    <div class="row">
        <banner/>
    </div>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <div class="list-group">
            <!-- 原始html中我们使用a标签实现页面跳转 -->
          <!-- <a class="list-group-item active" href="./about.html">About</a>
          <a class="list-group-item" href="./home.html">Home</a> -->

            <!-- vue中借助router-link标签实现路由的切换 -->
          <router-link class="list-group-item" active-class="active" to="/about">About</router-link>
          <router-link class="list-group-item" active-class="active" to="/home">Home</router-link>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel">
          <div class="panel-body">
              <!-- 指定路由的呈现位置 -->
             <router-view></router-view>
          </div>
        </div>
      </div>
    </div>
  </div>


</template>

<script>
// 引入组件
import Banner from './components/Banner.vue'



export default {
    name: "App",
    data() {
      return {
    
      }
    },
    components: { 
        Banner
     }

}
</script>


<style lang="css" scoped>

</style>
