// Vue/20-脚手架/hello_vue/24_src_多级路由/pages/Message.vue
<template>
  <div>
        <ul>
            <li>
                <a href="/message1">message001</a>&nbsp;&nbsp;
             </li>
             <li>
               <a href="/message2">message002</a>&nbsp;&nbsp;
             </li>
              <li>
               <a href="/message/3">message003</a>&nbsp;&nbsp;
            </li>
       </ul>
   </div>
</template>

<script>
export default {
    name:'Message'
}
</script>

<style>

</style>

// React/Router6/router-six/05-嵌套路由/pages/Message.jsx
import React from 'react'

export default function Message() {
  return (
    <ul>
        <li>
            <a href="/message1">message001</a>&nbsp;&nbsp;
        </li>
        <li>
            <a href="/message2">message002</a>&nbsp;&nbsp;
        </li>
        <li>
            <a href="/message/3">message003</a>&nbsp;&nbsp;
        </li>
    </ul>
  )
}
