// React/ReactStaging/hello-react/16-params传递参数/pages/Home/Message/index.jsx
import React, { Component } from 'react'
import Detail from './Detail';
import {Link,Route} from 'react-router-dom'

export default class Message extends Component {
  state={
    messageArr:[
      {id:1,title:'消息1'},
      {id:2,title:'消息2'},
      {id:3,title:'消息3'}
    ]
  }
  render() {
    const {messageArr} = this.state
    return (
       <div>
            <ul>
                {
                  messageArr.map((msgObj)=>{
                    return (
                      <li key={msgObj.id}>
                        {/* 向路由组件传递params参数 */}
                          <Link to={`/home/message/detail/${msgObj.id}/${msgObj.title}`}>{msgObj.title}</Link>
                      </li>
                    )
                  })
                }
            </ul>
            <hr/>
            {/* 声明接收params */}
            <Route path="/home/message/detail/:id/:title" component={Detail}/>
      </div>
    )
  }
}

// Vue/20-脚手架/hello_vue/26_src_replace/pages/Message.vue
<template>
  <div>
        <ul>
            <li v-for="item in messageList" :key="item.id">
                <!-- 跳转路由并携带params参数，to的字符串写法 -->
                <!-- <router-link :to="`/home/message/detail/${item.id}/${item.title}`">{{item.title}}</router-link>&nbsp;&nbsp; -->

                <!-- 跳转路由并携带params参数，to的对象写法 -->
                <router-link :to="{
                    name:'xiangqing',
                    query:{
                        id:item.id,
                        title:item.title
                    }
                }">
                    {{item.title}}
                </router-link>

             </li>
       </ul>
       <hr>
       <router-view></router-view>
   </div>
</template>

<script>
export default {
    name:'Message',
    data() {
        return {
            messageList:[
                {id:'001',title:'消息001'},          
                {id:'002',title:'消息002'},          
                {id:'003',title:'消息003'},          
            ]
        }
    },
}
</script>

<style>

</style>
