// Vue/20-脚手架/hello_vue/24_src_多级路由/App.vue
<template>


<div>
    <div class="row">
        <banner/>
    </div>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <div class="list-group">
            <!-- 原始html中我们使用a标签实现页面跳转 -->
          <!-- <a class="list-group-item active" href="./about.html">About</a>
          <a class="list-group-item" href="./home.html">Home</a> -->

            <!-- vue中借助router-link标签实现路由的切换 -->
          <router-link class="list-group-item" active-class="active" to="/about">About</router-link>
          <router-link class="list-group-item" active-class="active" to="/home">Home</router-link>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel">
          <div class="panel-body">
              <!-- 指定路由的呈现位置 -->
             <router-view></router-view>
          </div>
        </div>
      </div>
    </div>
  </div>


</template>

<script>
// 引入组件
import Banner from './components/Banner.vue'



export default {
    name: "App",
    data() {
      return {
    
      }
    },
    components: { 
        Banner
     }

}
</script>


<style lang="css" scoped>

</style>

// React/ReactStaging/hello-react/21-withRouter的使用/App.js
import React, { Component } from 'react'
import {Route,Switch,Redirect} from 'react-router-dom'

import Home from './pages/Home';   //路由组件
import About from './pages/About'  //路由组件
import Header from './components/Header';  //一般组件
import MyNavLink from './components/MyNavLink';

export default class App extends Component {
render() {
    return (
      <div>
        <Header/>
        <div className="row">
              <div className="col-xs-2 col-xs-offset-2">
                <div className="list-group">
                  {/* 原生heml中靠a跳转不同页面 */}
                  {/* <a className="list-group-item active" href="./about.html">About</a>
                  <a className="list-group-item" href="./home.html">Home</a> */}
    
                  {/* 在react中靠路由链接实现切换组件-编写路由链接 */}                
                    <MyNavLink to='/about'>About</MyNavLink>
                    <MyNavLink to='/home'>Home</MyNavLink>
                </div>
              </div>
              <div className="col-xs-6">
                <div className="panel">
                  <div className="panel-body">
                    {/* 注册路由 */}
                   <Switch>
                      <Route path="/about" component={About}/>
                      <Route path="/home" component={Home}/>
                      <Redirect to="/about"/>
                   </Switch>
                  </div>
                </div>
              </div>
        </div>
    </div>
    )
  }
}
