// React/ReactStaging/hello-react/05-github用户搜索案例/components/Search/index.jsx
import React, { Component } from 'react'
import axios from 'axios'

export default class Search extends Component {

  search=()=>{
    // 解构赋值的连续写法
    // keyWordElement是未被定义的
    const {keyWordElement:{value}}=this

    // 发送请求前更新app更新状态
    this.props.updateAppState({isFirst:false,isLoading:true})

    // 发送网络请求
    axios.get(`https://api.github.com/search/users?q=${value}`).then(
      (res)=>{
        // console.log('成功了',res.data);
        // this.props.saveUser(res.data.items)
        // 请求成功通知app更新状态
        this.props.updateAppState({isFirst:false,users:res.data.items,isLoading:false})
      },
      (error)=>{
        console.log('失败了');
        this.props.updateAppState({isFirst:false,err:error.message})
      }
    )
  }


  render() {
    return (
        <section className="jumbotron">
            <h3 className="jumbotron-heading">搜索GitHub用户</h3>
            <div>
                 <input ref={c => this.keyWordElement=c} type="text" placeholder="输入关键词搜索"/>&nbsp;
                 <button onClick={this.search}>搜索</button>
            </div>
        </section>
    )
  }
}

// Vue/20-脚手架/hello_vue/17_src_github搜索案例/components/Search.vue
<template>
      <section class="jumbotron">
      <h3 class="jumbotron-heading">Search Github Users</h3>
      <div>
        <input v-model="keyWorld" type="text" placeholder="enter the name you search"/>&nbsp;
        <button @click="searchUsers">Search</button>
      </div>
    </section>
</template>

<script>
import axios from 'axios';

export default {
    name:'Search',
    data() {
        return {
            keyWorld:''
        }
    },
    methods: {
        searchUsers(){
            // 请求前更新list的数据
            this.$bus.$emit('upDateListDate',{isFirst:false,isLoading:true,errMsg:'',users:[]});
            axios.get(`https://api.github.com/search/users?q=${this.keyWorld}`).then(
                response=>{
                    console.log('请求成功');
                    console.log(response.data.items);
                     this.$bus.$emit('upDateListDate',{isLoading:false,errMsg:'',users:response.data.items});
                },
                error=>{
                    console.log('请求失败后');
                    this.$bus.$emit('upDateListDate',{
                        isLoading:false,
                        errMsg:error.message,
                        users:[]
                        });
                }
            )
        }
    },

}
</script>

<style>

</style>
